export const products = [
    { 
        id: 'product1',
        url: 'https://cdn2.iconfinder.com/data/icons/buildings-53/128/50-512.png', 
        detailUrl: 'https://rukminim1.flixcart.com/image/416/416/kapoo7k0/electric-kettle/p/6/s/pigeon-favourite-original-imafs7xhj5uwgrh4.jpeg?q=70',
        shortTitle: 'Home & Kitchen',
        longTitle: 'Pigeon FAVOURITE Electric Kettle  (1.5 L, Silver, Black)', 
        mrp: 1195,
        cost: 625,
        discount: '47%',
        quantity: 1,
        description: 'This electric kettle from Pigeon will soon become a travelers best friend, a hostelite saviour and an answer to all the midnight cravings. With this handy appliance, you can boil water and use it to make instant noodles, packet soup, coffee and green tea.',
        discount_tag: 'Extra 10% Off', 
        tagline: 'Deal of the day' ,
        shopname:'Urban Tech Solutions',
        area:'Sakchi',
        category:'Electronics',
        contact:'9110 274 658',
        shopid:'shop1'
    },
    { 
        id: 'product2',
        url: 'https://cdn2.iconfinder.com/data/icons/buildings-53/128/50-512.png', 
        detailUrl: 'https://rukminim1.flixcart.com/image/416/416/kl6wx3k0/sandwich-maker/8/r/d/sandwich-01-flipkart-smartbuy-original-imagydds4zthxt8z.jpeg?q=70',
        shortTitle: 'Sandwich Makers',
        longTitle: 'Flipkart SmartBuy Sandwich 01 Grill  (Black)',
        mrp: 1499,
        cost: 899,
        discount: '40%',
        quantity: 1,
        description: 'This non-stick sandwich toaster .easy to use and very handy. Directly hold over flame to make tasty toasts and toasted sandwiches. Specially designed by keeping your needs in mind, the sandwich maker makes whatever youre doing simpler, smarter and better',
        discount_tag: 'From 99+5% Off', 
        tagline: 'Pestige, Nova & more' ,
        shopname:'Urban Tech Solutions',
        area:'Sakchi',
        category:'Electronics',
        contact:'9110 274 658',
        shopid:'shop1'
    },
    { 
        id: 'product3',
        url: 'https://img.freepik.com/premium-vector/sports-equipment-shop-icon-vector-graphics-use_1080480-129619.jpg', 
        detailUrl: 'https://rukminim1.flixcart.com/image/416/416/kohigsw0/resistance-tube/c/s/e/new-adjustable-single-resistance-tube-multicolor-na-ajro-deal-original-imag2xg88mhmwxz5.jpeg?q=70', 
        shortTitle: 'Fitness Gear',
        longTitle: 'AJRO DEAL New Adjustable Single Resistance Tube (Multicolor) Resistance Tube  (Multicolor)', 
        mrp: 499,
        cost: 166,
        discount: '66%',
        quantity: 1,
        description: 'This unique product can tone your back muscles, reduce belly fat, improve blood circulation and also improves your body posture. It increases the stamina, energy and vitality of the body. The elastic resistance of the rubber training rope can be used to train and exercise in whichever way you want, according to your physical needs.',
        discount_tag: 'Upto 70% Off', 
        tagline: 'Deal of the Day', 
        shopname:'Fitness Fusion',
        area:'Bistpur',
        category:'Fashion',
        contact:'9811132456',
        shopid:'shop2'
    },
    { 
        id: 'product4',
        url: 'https://www.leafio.ai/storage/attachments/112362ebcd25e105ea90868dd87b2954bc5d5207.webp', 
        detailUrl: 'https://rukminim1.flixcart.com/image/416/416/kll7bm80/smartwatch/c/1/n/43-mo-sw-sense-500-android-ios-molife-original-imagyzyycnpujyjh.jpeg?q=70',
        shortTitle: 'Smart Watches',
        longTitle: 'Molife Sense 500 Smartwatch  (Black Strap, Freesize)', 
        mrp: 6999,
        cost: 4049,
        discount: '42%',
        quantity: 1,
        description: 'The Molife Sense 500, a brilliant smartwatch with a beautiful large display. Say hello to the infinity 1.7-inch display with 2.5D curved edges. Thanks to seamless Bluetooth 5.0 connectivity, you wont have to keep waiting. Bring a change to your outfit every day with changeable straps. A splash of color every day keeps the boredom away.',
        discount_tag: 'Grab Now', 
        tagline: 'Best Seller',
        shopname:'TechNest Electronics',
        area:'Bistpur',
        category:'Electronics',
        contact:'234 567 8909',
        shopid:'shop3'
    },
    { 
        id: 'product5',
        url: 'https://c8.alamy.com/comp/KFNE81/electronics-store-with-copy-space-board-isolated-on-white-background-KFNE81.jpg',
        detailUrl: 'https://rukminim1.flixcart.com/image/416/416/k3uhhu80/hair-dryer/n/m/t/nova-2800-w-professional-nhp-8220-original-imafmvwfhmzsxdrw.jpeg?q=70', 
        shortTitle: 'Trimmers, Dryers & more',
        longTitle: 'Nova Professional NHP 8220 Hair Dryer  (1800 W, Multicolor)', 
        mrp: 1899,
        cost: 1124,
        discount: '40%',
        quantity: 1,
        description: '',
        discount_tag: 'From ₹499', 
        tagline: 'Kubra, Nova & more' ,
        shopname:'TechEase Electronics',
        area:'Sakchi',
        category:'Electronics',
        contact:'9870032109',
        shopid:'shop4'
    },
    { 
        id: 'product6',
        url: 'https://c8.alamy.com/comp/KFNE81/electronics-store-with-copy-space-board-isolated-on-white-background-KFNE81.jpg',
        detailUrl: 'https://rukminim1.flixcart.com/image/416/416/kk01pjk0/fan/d/d/l/tiktik-quiet-portable-table-fan-zigma-original-imafzg7ftzuckpad.jpeg?q=70', 
        shortTitle: 'Table Fans',
        longTitle: 'Portable 300 mm Ultra High Speed 3 Blade Table Fan  (Black, Pack of 1)', 
        mrp: 2250,
        cost: 1199,
        discount: '46%',
        quantity: 1,
        description: 'Table Fan. Perfect size fan for use on a table, desk or in an RV. Whisper quiet, powerful airflow and reliable operation in a compact 6" size. Two adjustable speeds to customize airflow: high or low settings. Tough break-resistant ABS plastic blades. ',
        discount_tag: 'Minimum 40% Off', 
        tagline: 'Top Selling' ,
        shopname:'TechEase Electronics',
        area:'Sakchi',
        category:'Electronics',
        contact:'9870032109',
        shopid:'shop4'
    },
    { 
        id: 'product7',
        url: 'https://www.shutterstock.com/image-vector/electronics-icon-vector-illustration-design-260nw-2065305404.jpg',
        detailUrl: 'https://rukminim1.flixcart.com/image/416/416/kcgk1ow0/headphone/n/u/a/235v2-fast-charging-boat-original-imaftk6us4af7bca.jpeg?q=70', 
        shortTitle: 'Headphones',
        longTitle: 'boAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset ', 
        mrp: 2990,
        cost: 1199,
        discount: '59%',
        quantity: 1,
        description: 'Let music brighten up your mood anytime, anywhere with the boAt 235v2 Fast Charging Bluetooth Headset. This Bluetooth headset features a Call Vibration Alert, a Fast Charging Technology, and Easy Access Controls to listen to and manage your favorite music with ease.',
        discount_tag: 'Minimum 50% Off', 
        tagline: 'Grab Now!' ,
        shopname:'Gadgets Galaxy',
        area:'Bistpur',
        category:'Mobile',
        contact:'234 567 8905',
        shopid:'shop5'
    },
    { 
        id: 'product8',
        url: 'https://www.shutterstock.com/image-vector/electronics-icon-vector-illustration-design-260nw-2065305404.jpg', 
        detailUrl: 'https://rukminim1.flixcart.com/image/200/200/khf63680/cases-covers/back-cover/d/7/g/spigen-acs02256-original-imafxfgbffqaugur.jpeg?q=70', 
        shortTitle: 'Mobile Covers',
        longTitle: 'Egotude Back Cover for iphone 16  (Black, Pack of: 1)', 
        mrp: 1990,
        cost: 599,
        discount: '10%',
        quantity: 1,
        description: 'Introducing the Egotude for iPhone 16 Stand Case, a translucent frosted matte back cover that not only protects your device but also enhances its style. Crafted with precision, this case is compatible with Mag technology, allowing seamless wireless charging and a secure magnetic attachment.',
        discount_tag: 'Minimum 10% Off', 
        tagline: 'Grab Now!' ,
        shopname:'Gadgets Galaxy',
        area:'Bistpur',
        category:'Mobile',
        contact:'234 567 8905',
        shopid:'shop5'
    },
    { 
        id: 'product9',
        url: 'https://thumbs.dreamstime.com/b/beauty-store-building-cosmetics-store-facade-beauty-store-building-city-street-facade-cosmetics-products-shop-vector-showcase-town-245687270.jpg',
        detailUrl: 'https://static.beautytocare.com/cdn-cgi/image/width=1600,height=1600,f=auto/media/catalog/product//n/i/nivea-aloe-vera-body-lotion-625ml.jpg', 
        shortTitle: 'Skin & Hair Care',
        longTitle: 'NIVEA Body Milk with Almond Oil Moisturizer for Very Dry Skin', 
        mrp: 625,
        cost: 250,
        discount: '95%',
        quantity: 1,
        description: 'NIVEA Nourishing Body Lotion is a rich, luxurious lotion that is ideal for extra dry and sensitive skin types that have lost their natural moisture. Enriched with skin softening essential almond oil and infused with deep moisture serum, NIVEA Nourishing Body Lotion intensively nourishes your skin for 48hours to noticeably reduce the dryness of your skin just after one application, leaving it soft, smooth and well moisturized.',
        discount_tag: 'From 99+5% Off', 
        tagline: 'Shampoos, Face Washes & More' ,
        shopname:'The Beauty Boutique ',
        area:'Sakchi',
        category:'Fashion',
        contact:'234 567 8913',
        shopid:'shop6'
    },
    { 
        id: 'product10',
        url: 'https://media.istockphoto.com/id/1091801740/vector/bags-and-shoes-shop-with-glassware-showcase.jpg?s=612x612&w=0&k=20&c=uoUrRFdwhCOw3xZY7QSokQqrE-TcB-35VPRCr1R_MhM=',
        detailUrl: 'https://rukminim1.flixcart.com/flap/200/200/image/74bc985c62f19245.jpeg?q=70', 
        shortTitle: 'Skybags & Safari',
        longTitle: 'Cabin Suitcase (55 cm) 4 Wheels - Magnum Fury 55', 
        mrp: 7365,
        cost: 1449,
        discount: '80%',
        quantity: 1,
        description: 'The cabin suitcase has a rugged construction with a durable polypropylene body, making it a stylish travel companion. It also has a sleek design that exudes elegance and charming aesthetics, ideal for a modern traveller.',
        discount_tag: 'Minimum 80% Off', 
        tagline: 'Grab Now!' ,
        shopname:'CityMart Essentials',
        area:'Bistpur',
        category:'Fashion',
        contact:'234 567 8901',
        shopid:'shop7'
    },
    { 
        id: 'product11',
        url: 'https://st4.depositphotos.com/19153102/22854/v/450/depositphotos_228541626-stock-illustration-sports-shop-shop-window-range.jpg',
        detailUrl: 'https://rukminim1.flixcart.com/flap/150/150/image/b616a7aa607d3be0.jpg?q=70', 
        shortTitle: 'Sports & Fitness Essentials',
        longTitle: 'Shopeleven DL6 Sports Solid wheel Roller Ab Exerciser  (Multicolor)', 
        mrp: 999,
        cost: 180,
        discount: '80%',
        quantity: 1,
        description: 'TARGETS ABS AND CORE FOR GREAT RESULTS; The Exercise Wheel tones and strengthens abs, arms and back muscles to help build strong tight core and ab muscles for back support and posture, ULTRA PORTABLE CONSTRUCTION - SO CONVENIENT; easy to assemble, our Abs Wheel is suitable for travelling, and manufactured from lightweight durable m, GREAT FOR ALL LEVELS; our Abb Roller Wheel is suitable for both beginners and advanced exercisers to develop balanced core strength., PREMIUM KNEE PAD AND FOAM HANDLES FOR COMFORT; our Exercise Roller Wheel includes a soft knee pad,, APPLICABLE - Abdominal exercise roller is suitable for men and women to restore body balance, ideal for beginners and experienced people',
        discount_tag: 'Upto 80% Off', 
        tagline: 'Ab Exerciser, Yoga & more' ,
        shopname:'FitZone Sportswear',
        area:'Sakchi',
        category:'Fashion',
        contact:'234 567 8911',
        shopid:'shop8'
    },
    { 
        id: 'product12',
        url: 'https://www.shutterstock.com/image-vector/furniture-market-icon-symbol-store-260nw-1140868265.jpg',
        detailUrl: 'https://rukminim1.flixcart.com/image/300/300/ke7ff680/hammock-swing/j/f/u/q3-jkaf-y3l0-furniture-kart-original-imafux96kpy7grch.jpeg?q=70', 
        shortTitle: 'Hammock And Swings',
        longTitle: 'Furniture kart Luxury Hammock Chair with Stand for Adults Balcony Steel Large Swing', 
        mrp: 9999,
        cost: 4999,
        discount: '80%',
        quantity: 1,
        description: 'Ideal for Deck, balcony & more - Unique swing Chair is the perfect addition to any space like backyard patio, deck, in a sun-room or garden, or near a pool, or outdoor bar -:- Premium Fluffy Cushion - It comes with a Soft deep fluffy cushion, perfect for you to snuggle in on a warm and sunny day, with a book and a cold coffee -:- Use Indoors or Outdoors',
        discount_tag: 'From ₹1999', 
        tagline: 'Trendy Collection' ,
        shopname:'Eco Goods',
        area:'Sakchi',
        category:'Home',
        contact:'234 567 8915',
        shopid:'shop9'
    },
    { 
        id: 'product13',
        url: 'https://www.shutterstock.com/image-vector/furniture-market-icon-symbol-store-260nw-1140868265.jpg',
        detailUrl: 'https://rukminim1.flixcart.com/image/300/300/bean-bag/h/v/b/f8-the-furniture-store-xxxl-original-imae65d3wg7qzpkn.jpeg?q=70', 
        shortTitle: 'Bean Bag Covers',
        longTitle: 'GIGLICK 4XL Faux Leather Bean Bag Filled with Beans | Ready To Use Teardrop Bean Bag With Bean Filling', 
        mrp: 4999,
        cost: 1499,
        discount: '80%',
        quantity: 1,
        description: 'Designed and made in INDIA, our luxury bean bags are made in India with leatherette fabric with Over Locked Stitching and Double Protected with Velcro and Zipper for safety, 4XL Size: 90X90X110 CM. Available in different colours to accommodate your preference.',
        discount_tag: 'Upto 80% Off', 
        tagline: 'XL, XXL & More' ,
        shopname:'Eco Goods',
        area:'Sakchi',
        category:'Home',
        contact:'234 567 8915',
        shopid:'shop9'

    },
    { 
        id: 'product14',
        url: 'https://thumbs.dreamstime.com/b/pet-shop-facade-vector-cartoon-style-illustration-pet-shop-facade-bright-banner-store-building-exterior-isolated-white-110938937.jpg',
        detailUrl: 'https://rukminim1.flixcart.com/image/300/300/jlcmavk0/aquarium-tank/s/4/5/usb-desktop-aquarium-with-running-water-calendar-temperature-and-original-imaf8hv4nkv55gx8.jpeg?q=70', 
        shortTitle: 'Aquarium Tank',
        longTitle: 'Aquastar Chicos Breeding Acrylic Aquarium Guppy/Betta Transparent Isolation Box (1 L) Rectangle Aquarium Tank  (1 L)', 
        mrp: 999,
        cost: 480,
        discount: '80%',
        quantity: 1,
        description: 'Aquarium Chicos Breeder Box is a specialized enclosure designed for aquarists and fish breeders to safely house and nurture newborn or juvenile fish within a larger aquarium system. The breeder box typically features a transparent acrylic or plastic construction, allowing for clear observation of the inhabitants inside. Its designed to be easily affixed to the walls of the main aquarium using suction cups or brackets, providing stability and security.',
        discount_tag: 'Upto 80% Off', 
        tagline: 'Flat, Round, Cube & More' ,
        shopname:'Pet Corner',
        area:'Bistpur',
        category:'Beauty, Toys & More',
        contact:'234 567 8914',
        shopid:'shop10'
    },
    { 
        id: 'product15',
        url: 'https://media.istockphoto.com/id/1277082581/vector/furniture-shop-exterior.jpg?s=612x612&w=0&k=20&c=J3N2mp0c555kAmNQMM5lIwjnnhrCy8JOaPBnMYFl9eY=',
        detailUrl: 'https://rukminim1.flixcart.com/image/300/300/jffpoy80/office-study-chair/v/v/z/pp-am-5001cb-apex-original-imaf3u8rbr5cdycv.jpeg?q=70', 
        shortTitle: 'Office & Study Chairs',
        longTitle: 'FUGO FUGO® by Nice Goods, MODEL : NG-13B, Ergonomic Executive High Back Office Chair Leather Office Arm Chair ', 
        mrp: 12000,
        cost: 5539,
        discount: '80%',
        quantity: 1,
        description: 'The comfortable office chair uses a breathable mesh design to prevent the accumulation of sweat and heat. The high-density sponge cushion is soft and breathable. ADJUSTABILITY: Backrest can be reclined up to 135 degrees along with the seat and armrest. The chair can be rotated 360 degrees and can be rolled easily with the swivel caster wheels.',
        discount_tag: 'Upto 80% Off', 
        tagline: 'Fabric & Leatherette' ,
        shopname:'Vintage Charm',
        area:'Sakchi',
        category:'Home',
        contact:'234 567 8917',
        shopid:'shop11'
    },
    { 
        id: 'product16',
        url: 'https://media.istockphoto.com/id/1277082581/vector/furniture-shop-exterior.jpg?s=612x612&w=0&k=20&c=J3N2mp0c555kAmNQMM5lIwjnnhrCy8JOaPBnMYFl9eY=',
        detailUrl: 'https://rukminim1.flixcart.com/image/300/300/jvcp9jk0/recliner/z/w/x/brown-top-grain-leather-sf7018011-1-royaloak-original-imafg9s9hh9vzpf3.jpeg?q=70', 
        shortTitle: 'Recliner',
        longTitle: '@Home by nilkamal Fabric Manual Recliner  (Finish Color - Cocoa, DIY(Do-It-Yourself))', 
        mrp: 90990,
        cost: 24480,
        discount: '80%',
        quantity: 1,
        description: 'Relaxing at home is a pleasure with the plush and ergonomic Matt Sofa Recliner. With pocket springs and S-springs in the seats and a 2-inch webbed back, this recliner is exceptionally comfortable for two. Its thick foam seats with cup holders and a reclining mechanism bring theatre-like experiences home. Rely on its sturdy pinewood frame and 260-gsm cotton polyester upholstery for hours of comfortable sitting. Get the Matt two-seater recliner for your home today.',
        discount_tag: 'Upto 80% Off', 
        tagline: 'Bantia, RoyalOak & More' ,
        shopname:'Vintage Charm',
        area:'Sakchi',
        category:'Home',
        contact:'234 567 8917',
        shopid:'shop11'
    },
    { 
        id: 'product17',
        url: 'https://us.123rf.com/450wm/lar01joka/lar01joka2202/lar01joka220200418/182461111-isolated-front-view-furniture-store-building-vector.jpg',
        detailUrl: 'https://rukminim1.flixcart.com/image/300/300/jlqwpe80-1/tv-entertainment-unit/d/t/f/particle-board-holland-tv-unit-black-forzza-black-original-imaf8t5ybywcdtys.jpeg?q=70', 
        shortTitle: 'Tv Units',
        longTitle: 'Perfect Homes Webster Engineered Wood TV Entertainment Unit  (Finish Color - Chocolate Wenge, Knock Down)', 
        mrp: 32999,
        cost: 10599,
        discount: '80%',
        quantity: 1,
        description: 'TV Unit is our exclusive creation and perfect companion for your TV. Dual tone finish in warm Black & White will add warmth to your home interiors. With flat utility shelves and compartments it offers loads of storage space to create a cozy home for your entertainment devices such as Set top Box, Video Players, Gaming Boxes, Remotes as well as Books, favorite photo frames or antique display items',
        discount_tag: 'From ₹2100', 
        tagline: 'Forzza, Zuari & more' ,
        shopname:'HomeStyle Décor',
        area:'Bistpur',
        category:'Home',
        contact:'234 567 8906',
        shopid:'shop12'
    },
    { 
        id: 'product18',
        url: 'https://us.123rf.com/450wm/lar01joka/lar01joka2202/lar01joka220200418/182461111-isolated-front-view-furniture-store-building-vector.jpg',
        detailUrl: 'https://rukminim1.flixcart.com/image/300/300/inflatable-sofa/6/j/s/wsb031a-velvet-wds-original-imaeaphzbkgrz3xp.jpeg?q=70', 
        shortTitle: 'Inflatable Sofas',
        longTitle: 'UBRON Car Inflatable Sofa With 2 pillow and Air pump Use For Travelling Leatherette 2 Seater Inflatable Sofa ', 
        mrp: 5999,
        cost: 1299,
        discount: '80%',
        quantity: 1,
        description: 'Featuring convenience, this inflatable sofa stands out with its detachable design, making it easy to carry and maintain. Further, its waterproof construction adds to its durability while ensuring hassle-free cleaning. Moreover, its high resilience provides excellent back support, relieving you from any discomfort during long trips.',
        discount_tag: 'Upto 80% Off', 
        tagline: 'Furn Central & more' ,
        shopname:'HomeStyle Décor',
        area:'Bistpur',
        category:'Home',
        contact:'234 567 8906',
        shopid:'shop12'
    },
        {
            id: 'product19',
            url: 'https://img.lovepik.com/photo/45011/7027.jpg_wh860.jpg',
            detailUrl: 'https://m.media-amazon.com/images/I/81skhWMDoPL._AC_UF894,1000_QL80_.jpg',
            shortTitle: 'Portable Blender',
            longTitle: 'NutriMix Portable Blender with Rechargeable Battery and 4 Blades',
            mrp: 2499,
            cost: 799,
            discount: '68%',
            quantity: 1,
            description: 'A compact and efficient blender for smoothies and shakes on the go. It features a rechargeable battery, stainless steel blades, and an ergonomic design, making it perfect for travel and daily use.',
            discount_tag: 'Flat 68% Off',
            tagline: 'Health Essentials',
            shopname: 'TechMart Store',
            area: 'Adityapur',
            category: 'Electronics',
            contact: '567 890 1234',
            shopid: 'shop13',
        },
        {
            id: 'product20',
            url: 'https://cdni.iconscout.com/illustration/premium/thumb/home-furniture-shop-illustration-download-in-svg-png-gif-file-formats--store-living-room-pack-e-commerce-shopping-illustrations-4245507.png',
            detailUrl: 'https://d35l77wxi0xou3.cloudfront.net/opencart/image/productFromFeb2020/Ceramic%20flower%20Pot1582791149-600x600.jpg',
            shortTitle: 'Ceramic Flower Pot',
            longTitle: 'Elegant Ceramic Flower Pot with Minimalist Design - 8 inches',
            mrp: 999,
            cost: 499,
            discount: '50%',
            quantity: 1,
            description: 'Enhance your home’s decor with this chic ceramic flower pot. Designed to suit any setting, it’s durable, lightweight, and ideal for indoor plants.',
            discount_tag: 'Flat 50% Off',
            tagline: 'Bring Nature Home',
            shopname: 'Blossom Studio',
            area: 'Adityapur',
            category: 'Home',
            contact: '789 012 3456',
            shopid: 'shop14',
        },
        {
            id: 'product21',
            url: 'https://www.shutterstock.com/image-vector/clothing-store-vector-illustration-by-260nw-2431459781.jpg',
            detailUrl: 'https://www.primeporter.com/cdn/shop/products/MFPRIMEPP2120_1copy_1200x1200.jpg?v=1638005261',
            shortTitle: 'Cotton Shirt',
            longTitle: 'Premium Cotton Shirt for Men - Slim Fit, White with Blue Stripes',
            mrp: 1499,
            cost: 899,
            discount: '40%',
            quantity: 1,
            description: 'Crafted with premium cotton, this shirt offers a comfortable slim fit with a modern striped design. Perfect for both casual and formal occasions.',
            discount_tag: 'Flat 40% Off',
            tagline: 'Trendy Fashion',
            shopname: 'Style Bazaar',
            area: 'Adityapur',
            category: 'Fashion',
            contact: '123 456 7890',
            shopid: 'shop15',
        },
        {
            id: 'product22',
            url: 'https://img.freepik.com/premium-vector/outdoor-view-bookstore-building-with-books_208536-273.jpg',
            detailUrl: 'https://m.media-amazon.com/images/I/61M6KzUbf7L._AC_UF1000,1000_QL80_.jpg',
            shortTitle: 'Self-Help Book',
            longTitle: 'Atomic Habits by James Clear - Build Good Habits & Break Bad Ones',
            mrp: 799,
            cost: 599,
            discount: '25%',
            quantity: 1,
            description: 'A life-changing book offering practical strategies to build better habits and improve every day. Ideal for personal growth and productivity enthusiasts.',
            discount_tag: 'Limited Time Offer',
            tagline: 'Knowledge Corner',
            shopname: 'Book Haven',
            area: 'Adityapur',
            category: 'Beauty, Toys & More',
            contact: '345 678 9012',
            shopid: 'shop16',
        },
        {
            id: 'product23',
            url: 'https://i.pinimg.com/474x/31/de/dd/31dedd1aeacbb1c64b3b9ed8f7e0af2e.jpg',
            detailUrl: 'https://m.media-amazon.com/images/I/719FC-Ald7L.jpg',
            shortTitle: 'Basmati Rice',
            longTitle: 'Premium Basmati Rice - 5kg Pack, Long-Grain and Aromatic',
            mrp: 799,
            cost: 599,
            discount: '25%',
            quantity: 1,
            description: 'High-quality basmati rice with long grains and a rich aroma, perfect for biryanis and daily meals.',
            discount_tag: 'Flat 25% Off',
            tagline: 'Staple Food Essentials',
            shopname: 'Daily Fresh Mart',
            area: 'Sakchi',
            category: 'Grocery',
            contact: '987 654 3210',
            shopid: 'shop17',
        },
        {
            id: 'product24',
            url: 'https://i.pinimg.com/474x/31/de/dd/31dedd1aeacbb1c64b3b9ed8f7e0af2e.jpg',
            detailUrl: 'https://naturelandorganics.com/cdn/shop/files/SUFLOWEROIL_1200x1200.png?v=1708080399',
            shortTitle: 'Sunflower Oil',
            longTitle: 'Healthy Sunflower Oil - 1L, Rich in Vitamin E',
            mrp: 180,
            cost: 149,
            discount: '17%',
            quantity: 1,
            description: 'Refined sunflower oil with a neutral taste and high Vitamin E content. Suitable for all types of cooking and frying.',
            discount_tag: 'Save 17%',
            tagline: 'Healthy Living',
            shopname: 'Daily Fresh Mart',
            area: 'Sakchi',
            category: 'Grocery',
            contact: '987 654 3210',
            shopid: 'shop17',
        },
        {
            id: 'product25',
            url: 'https://cdni.iconscout.com/illustration/premium/thumb/travel-agency-business-illustration-download-in-svg-png-gif-file-formats--shop-store-doorfront-pack-people-illustrations-4391267.png?f=webp',
            detailUrl: 'https://www.informalnewz.com/wp-content/uploads/2023/09/Flight-Tickets-Rule.jpg',
            shortTitle: 'Flight Tickets',
            longTitle: 'Round-Trip Flight Tickets - Domestic & International',
            mrp: 15000,
            cost: 12999,
            discount: '13%',
            quantity: 1,
            description: 'Book your flight tickets with ease for both domestic and international destinations. Special discounts for early bookings.',
            discount_tag: 'Special Offer',
            tagline: 'Explore the World',
            shopname: 'Skyline Travel Agency',
            area: 'Bistpur',
            category: 'Travel',
            contact: '987 654 3210',
            shopid: 'shop18',
        },
        {
            id: 'product26',
            url: 'https://cdni.iconscout.com/illustration/premium/thumb/travel-agency-business-illustration-download-in-svg-png-gif-file-formats--shop-store-doorfront-pack-people-illustrations-4391267.png?f=webp',
            detailUrl: 'https://s3-eu-west-1.amazonaws.com/goldcar/goldcarweb/landings/full/travel-car-rental.jpeg',
            shortTitle: 'Car Rentals',
            longTitle: 'Affordable Car Rentals - Sedan, SUV, and Luxury Cars',
            mrp: 2500,
            cost: 1999,
            discount: '20%',
            quantity: 1,
            description: 'Rent a car for your road trips or local travel needs. Choose from a wide range of vehicles including economy, SUV, and luxury cars.',
            discount_tag: 'Flat 20% Off',
            tagline: 'Drive Your Journey',
            shopname: 'Skyline Travel Agency',
            area: 'Bistpur',
            category: 'Travel',
            contact: '987 654 3210',
            shopid: 'shop18',
        },
        {
            id: 'product27',
            url: 'https://media.istockphoto.com/id/1432598511/vector/businesswoman-works-in-travel-agency-banner-with-man-holding-telescope-in-snowy-mountains.jpg?s=612x612&w=0&k=20&c=7iBSaPcShQ1bl-7vXNeGv1OQkEcED3SKoOQzK1KqSyw=',
            detailUrl: 'https://5.imimg.com/data5/WW/YU/FP/SELLER-16373292/hotel-bookings-service-500x500.png',
            shortTitle: 'Hotel Bookings',
            longTitle: 'Premium Hotel Stays - 5-Star to Budget Hotels',
            mrp: 5000,
            cost: 3999,
            discount: '20%',
            quantity: 1,
            description: 'Book luxurious 5-star accommodations or budget-friendly stays with exciting discounts. Available in major tourist destinations.',
            discount_tag: 'Save 20%',
            tagline: 'Stay in Comfort',
            shopname: 'DreamGateaways',
            area: 'Adityapur',
            category: 'Travel',
            contact: '345 678 9123',
            shopid: 'shop19',
        },
        {
            id: 'product28',
            url: 'https://media.istockphoto.com/id/1432598511/vector/businesswoman-works-in-travel-agency-banner-with-man-holding-telescope-in-snowy-mountains.jpg?s=612x612&w=0&k=20&c=7iBSaPcShQ1bl-7vXNeGv1OQkEcED3SKoOQzK1KqSyw=',
            detailUrl: 'https://www.setmytrip.in/wp-content/uploads/2024/09/PSX_20220420_181026-1067x800.webp',
            shortTitle: 'Beach Resort Package',
            longTitle: '3-Night Stay at Exotic Beach Resort with Complimentary Breakfast',
            mrp: 18000,
            cost: 14999,
            discount: '17%',
            quantity: 1,
            description: 'Enjoy a luxurious 3-night stay at a scenic beach resort. Package includes complimentary breakfast, pool access, and sightseeing options.',
            discount_tag: 'Limited Time Offer',
            tagline: 'Relax & Unwind',
            shopname: 'DreamGateaways',
            area: 'Adityapur',
            category: 'Travel',
            contact: '345 678 9123',
            shopid: 'shop19',
        }

];